# Generated by Django 5.2.15 on 2026-09-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_base', models.CharField(max_length=500)),
                ('model_name', models.CharField(max_length=255)),
                ('api_key', models.CharField(blank=True, max_length=2000)),
                ('ca_cert', models.TextField(blank=True, help_text="PEM-encoded CA certificate, only needed if the endpoint's TLS certificate isn't signed by a publicly trusted CA.")),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'llm_models',
                'ordering': ['-created_at'],
            },
        ),
    ]
