# Generated by Django 5.2.15 on 2026-07-03 09:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_destination', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datadestination',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='datadestination',
            name='password',
        ),
        migrations.RemoveField(
            model_name='datadestination',
            name='username',
        ),
        migrations.AddField(
            model_name='datadestination',
            name='configuration',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='datadestination',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='datadestination',
            name='destination_type',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('sqlserver', 'SQL Server'), ('oracle', 'Oracle'), ('snowflake', 'Snowflake'), ('delta_lake', 'Delta Lake'), ('aws_s3', 'AWS S3'), ('azure_blob', 'Azure Blob'), ('minio', 'MinIO')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datadestination',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
