# Generated by Django 5.2.15 on 2026-07-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_destination', '0002_remove_datadestination_endpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadestination',
            name='destination_type',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('mongo', 'MongoDB'), ('sqlserver', 'SQL Server'), ('oracle', 'Oracle'), ('snowflake', 'Snowflake'), ('delta_lake', 'Delta Lake'), ('aws_s3', 'AWS S3'), ('azure_blob', 'Azure Blob'), ('minio', 'MinIO')], max_length=50),
        ),
    ]
