# Generated by Django 5.2.15 on 2026-08-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_destination', '0003_alter_datadestination_destination_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadestination',
            name='destination_type',
            field=models.CharField(choices=[('minio', 'MinIO')], max_length=50),
        ),
    ]
