# Generated by Django 5.2.15 on 2026-09-11 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0005_ingestionpipeline_ingest_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RagChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_chunks', to='ingestion.ingestionpipeline')),
            ],
            options={
                'db_table': 'rag_chunk',
                'ordering': ['pipeline_id', 'chunk_index'],
                'indexes': [models.Index(fields=['pipeline'], name='rag_chunk_pipelin_6bc080_idx')],
            },
        ),
    ]
