# Generated by Django 5.2.15 on 2026-07-02 12:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_destination', '0001_initial'),
        ('data_sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sync_interval', models.PositiveSmallIntegerField(help_text='Sync interval in hours (1-24)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='data_destination.datadestination')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='data_sources.datasource')),
            ],
            options={
                'db_table': 'ingestion_pipeline',
                'ordering': ['-created_at'],
            },
        ),
    ]
