# Generated by Django 5.2.15 on 2026-08-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionpipeline',
            name='nifi_destination_processor_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ingestionpipeline',
            name='nifi_last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingestionpipeline',
            name='nifi_process_group_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ingestionpipeline',
            name='nifi_source_processor_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ingestionpipeline',
            name='nifi_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
