# Generated by Django 5.2.15 on 2026-09-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_ingestionpipeline_nifi_destination_processor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionpipeline',
            name='source_object',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
