# Generated by Django 5.2.15 on 2026-09-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_pipelinerun'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionpipeline',
            name='ingest_mode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ingestionpipeline',
            name='raw_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ingestionpipeline',
            name='raw_object_bucket',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ingestionpipeline',
            name='raw_object_key',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
