# Generated by Django 5.2.15 on 2026-09-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_bi_tool',
            field=models.CharField(choices=[('METABASE', 'Metabase'), ('SUPERSET', 'Superset')], default='METABASE', max_length=20),
        ),
    ]
