# Generated by Django 5.2.15 on 2026-09-11 06:32

from django.db import migrations, models


def remap_legacy_user_role(apps, schema_editor):
    # Role.USER no longer exists - map any existing rows to the new
    # least-privileged default before the choices constraint changes.
    User = apps.get_model("users", "User")
    User.objects.filter(role="USER").update(role="DATA_ANALYST")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_active_bi_tool'),
    ]

    operations = [
        migrations.RunPython(remap_legacy_user_role, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DATA_ENGINEER', 'Data Engineer'), ('DATA_ANALYST', 'Data Analyst')], default='DATA_ANALYST', max_length=20),
        ),
    ]
