# Generated by Django 5.2.15 on 2026-09-04 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_sources', '0005_alter_datasource_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_text', models.TextField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], max_length=20)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_history', to='data_sources.datasource')),
            ],
            options={
                'verbose_name_plural': 'Query history',
                'db_table': 'query_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
