# Generated by Django 5.2.15 on 2026-09-04 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0005_alter_datasource_source_type'),
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryhistory',
            name='trino_user',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='queryhistory',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='query_history', to='data_sources.datasource'),
        ),
        migrations.AlterField(
            model_name='queryhistory',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('denied', 'Denied')], max_length=20),
        ),
    ]
