# Generated by Django 5.2.15 on 2026-07-03 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='password',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='username',
        ),
        migrations.AddField(
            model_name='datasource',
            name='configuration',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='datasource',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('minio', 'MinIO'), ('aws_s3', 'AWS S3'), ('azure_blob', 'Azure Blob'), ('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('sqlserver', 'SQL Server'), ('oracle', 'Oracle'), ('sharepoint', 'SharePoint'), ('rest_api', 'REST API'), ('ftp', 'FTP'), ('sftp', 'SFTP')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
