# Generated by Django 5.2.15 on 2026-07-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0002_remove_datasource_endpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('minio', 'MinIO'), ('mongo', 'MongoDB'), ('aws_s3', 'AWS S3'), ('azure_blob', 'Azure Blob'), ('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('sqlserver', 'SQL Server'), ('oracle', 'Oracle'), ('sharepoint', 'SharePoint'), ('rest_api', 'REST API'), ('ftp', 'FTP'), ('sftp', 'SFTP')], max_length=50),
        ),
    ]
