# Generated by Django 5.2.15 on 2026-08-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0003_alter_datasource_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('mongo', 'MongoDB'), ('postgres', 'PostgreSQL')], max_length=50),
        ),
    ]
