# Generated by Django 5.2.15 on 2026-09-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sources', '0005_alter_datasource_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('mongo', 'MongoDB'), ('postgres', 'PostgreSQL'), ('kafka', 'Kafka'), ('google_drive', 'Google Drive')], max_length=50),
        ),
    ]
