"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load BASE_DIR/.env (gitignored) into the environment so os.getenv() below can
# pick up real secrets instead of always falling back to their hardcoded defaults.
# No dotenv dependency needed - the file is a plain KEY=VALUE list.
_env_path = BASE_DIR / ".env"
if _env_path.exists():
    for _line in _env_path.read_text(encoding="utf-8").splitlines():
        _line = _line.strip()
        if not _line or _line.startswith("#") or "=" not in _line:
            continue
        _key, _value = _line.split("=", 1)
        os.environ.setdefault(_key.strip(), _value.strip())


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=wwjaefvd%arg_0qufn^ws^-)*oz6o!z!p+lqtkpm1@idl4sr3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "datalake.augtrans.com",
    "localhost",
    "127.0.0.1",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "apps.users",
    "apps.data_sources",
    "apps.data_destination",
    "apps.ingestion",
    "apps.query",
    "apps.catalog",
    "apps.playground",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#########################################################################

# Authentication settings
AUTH_USER_MODEL = "users.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "BLACKLIST_AFTER_ROTATION": True,
}

CORS_ALLOWED_ORIGINS = [
   "http://localhost:4200",
]

CORS_ALLOW_ALL_ORIGINS = True

CSRF_TRUSTED_ORIGINS = [
    "http://datalake.augtrans.com",
    "https://datalake.augtrans.com",
    "http://localhost:4200"
]

NIFI_URL = os.getenv(
    "NIFI_URL",
    "https://localhost:8443/nifi-api",
)

NIFI_JDBC_DRIVER_PATH = os.getenv(
    "NIFI_JDBC_DRIVER_PATH",
    "/opt/nifi/nifi-current/drivers/postgresql.jar",
)

NIFI_USERNAME = os.getenv(
    "NIFI_USERNAME",
    "shubham",
)

NIFI_PASSWORD = os.getenv(
    "NIFI_PASSWORD",
    "Shubham@123456",
)

NIFI_ROOT_PROCESS_GROUP_ID = os.getenv(
    "NIFI_ROOT_PROCESS_GROUP_ID",
    "",
)

ICEBERG_REST_URL = os.getenv(
    "ICEBERG_REST_URL",
    "http://localhost:8181",
)

# Used by the ingestion Spark job, which runs *inside* the spark-master
# container via `docker exec` - needs Docker-internal hostnames, unlike
# ICEBERG_REST_URL above which Django (on the host) talks to directly.
SPARK_ICEBERG_REST_URL = os.getenv(
    "SPARK_ICEBERG_REST_URL",
    "http://iceberg-rest:8181",
)

SPARK_MINIO_ENDPOINT = os.getenv(
    "SPARK_MINIO_ENDPOINT",
    "http://minio:9000",
)

# Host paths bind-mounted into the throwaway spark-submit container - see
# spark_runner.py. BASE_DIR is Backend/core, so its grandparent is the repo
# root containing Docker/.
_REPO_ROOT = BASE_DIR.parent.parent

SPARK_APPS_HOST_PATH = os.getenv(
    "SPARK_APPS_HOST_PATH",
    str(_REPO_ROOT / "Docker" / "apps"),
)

SPARK_IVY_CACHE_HOST_PATH = os.getenv(
    "SPARK_IVY_CACHE_HOST_PATH",
    str(_REPO_ROOT / "Docker" / "ivy-cache"),
)

OLLAMA_URL = os.getenv(
    "OLLAMA_URL",
    "http://localhost:11434",
)

OLLAMA_MODEL = os.getenv(
    "OLLAMA_MODEL",
    "qwen2.5:1.5b",
)

METABASE_URL = os.getenv(
    "METABASE_URL",
    "http://localhost:3000",
)

METABASE_API_KEY = os.getenv("METABASE_API_KEY", "")

TRINO_HOST = os.getenv("TRINO_HOST", "localhost")
TRINO_PORT = int(os.getenv("TRINO_PORT", "8082"))
TRINO_CATALOG = os.getenv("TRINO_CATALOG", "iceberg")